language: rust
dist: trusty
sudo: required
addons:
  firefox: latest-esr
  chrome: stable
before_script:
  - curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
  - echo "deb https://deb.nodesource.com/node_8.x trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install nodejs -y
  - npm install && npm run bundle
  - rustup component add rustfmt-preview
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt --all -- --check
  - npx karma start --single-run --browsers FirefoxHeadless karma.conf.js
  - npx karma start --single-run --browsers ChromeHeadless karma.conf.js
  - npm run lint
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true
cache:
  cargo: true
  directories:
    - node_modules
before_deploy:
  - cargo doc --verbose --no-deps
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/doc
  on:
    branch: master
    rust: stable
