(function() {var implementors = {};
implementors["actix_web"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"bytes/bytes/struct.Bytes.html\" title=\"struct bytes::bytes::Bytes\">Bytes</a>&gt; for <a class=\"enum\" href=\"actix_web/enum.Binary.html\" title=\"enum actix_web::Binary\">Binary</a>",synthetic:false,types:["actix_web::body::Binary"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for <a class=\"enum\" href=\"actix_web/ws/enum.OpCode.html\" title=\"enum actix_web::ws::OpCode\">OpCode</a>",synthetic:false,types:["actix_web::ws::proto::OpCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u16.html\">u16</a>&gt; for <a class=\"enum\" href=\"actix_web/ws/enum.CloseCode.html\" title=\"enum actix_web::ws::CloseCode\">CloseCode</a>",synthetic:false,types:["actix_web::ws::proto::CloseCode"]},];
implementors["backtrace"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;<a class=\"struct\" href=\"backtrace/struct.BacktraceFrame.html\" title=\"struct backtrace::BacktraceFrame\">BacktraceFrame</a>&gt;&gt; for <a class=\"struct\" href=\"backtrace/struct.Backtrace.html\" title=\"struct backtrace::Backtrace\">Backtrace</a>",synthetic:false,types:["backtrace::capture::Backtrace"]},];
implementors["resolv_conf"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"https://doc.rust-lang.org/nightly/std/net/ip/enum.IpAddr.html\" title=\"enum std::net::ip::IpAddr\">IpAddr</a>&gt; for <a class=\"enum\" href=\"resolv_conf/enum.ScopedIp.html\" title=\"enum resolv_conf::ScopedIp\">ScopedIp</a>",synthetic:false,types:["resolv_conf::ip::ScopedIp"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"https://doc.rust-lang.org/nightly/std/net/ip/enum.IpAddr.html\" title=\"enum std::net::ip::IpAddr\">IpAddr</a>&gt; for &amp;'a <a class=\"enum\" href=\"resolv_conf/enum.ScopedIp.html\" title=\"enum resolv_conf::ScopedIp\">ScopedIp</a>",synthetic:false,types:["resolv_conf::ip::ScopedIp"]},];
implementors["trust_dns_proto"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"trust_dns_proto/xfer/dns_request/struct.DnsRequest.html\" title=\"struct trust_dns_proto::xfer::dns_request::DnsRequest\">DnsRequest</a>&gt; for <a class=\"struct\" href=\"trust_dns_proto/op/message/struct.Message.html\" title=\"struct trust_dns_proto::op::message::Message\">Message</a>",synthetic:false,types:["trust_dns_proto::op::message::Message"]},];
implementors["unicase"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"unicase/struct.UniCase.html\" title=\"struct unicase::UniCase\">UniCase</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt;",synthetic:false,types:["unicase::UniCase"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>&gt; for <a class=\"struct\" href=\"unicase/struct.UniCase.html\" title=\"struct unicase::UniCase\">UniCase</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>&gt;",synthetic:false,types:["unicase::UniCase"]},];
implementors["unicode_bidi"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for <a class=\"struct\" href=\"unicode_bidi/level/struct.Level.html\" title=\"struct unicode_bidi::level::Level\">Level</a>",synthetic:false,types:["unicode_bidi::level::Level"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
