(function() {var implementors = {};
implementors["actix_web"] = [{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"actix_web/client/struct.ClientConnectorStats.html\" title=\"struct actix_web::client::ClientConnectorStats\">ClientConnectorStats</a>",synthetic:false,types:["actix_web::client::connector::ClientConnectorStats"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"actix_web/client/struct.Resume.html\" title=\"struct actix_web::client::Resume\">Resume</a>",synthetic:false,types:["actix_web::client::connector::Resume"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"actix_web/client/struct.Connect.html\" title=\"struct actix_web::client::Connect\">Connect</a>",synthetic:false,types:["actix_web::client::connector::Connect"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"actix_web/client/struct.Pause.html\" title=\"struct actix_web::client::Pause\">Pause</a>",synthetic:false,types:["actix_web::client::connector::Pause"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"actix_web/server/struct.PauseServer.html\" title=\"struct actix_web::server::PauseServer\">PauseServer</a>",synthetic:false,types:["actix_web::server::PauseServer"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"actix_web/server/struct.ResumeServer.html\" title=\"struct actix_web::server::ResumeServer\">ResumeServer</a>",synthetic:false,types:["actix_web::server::ResumeServer"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"actix_web/server/struct.StopServer.html\" title=\"struct actix_web::server::StopServer\">StopServer</a>",synthetic:false,types:["actix_web::server::StopServer"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"enum\" href=\"actix_web/ws/enum.Message.html\" title=\"enum actix_web::ws::Message\">Message</a>",synthetic:false,types:["actix_web::ws::Message"]},];
implementors["tamawiki"] = [{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"tamawiki/store/struct.Push.html\" title=\"struct tamawiki::store::Push\">Push</a>",synthetic:false,types:["tamawiki::store::Push"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"tamawiki/store/struct.Seq.html\" title=\"struct tamawiki::store::Seq\">Seq</a>",synthetic:false,types:["tamawiki::store::Seq"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"tamawiki/store/struct.Since.html\" title=\"struct tamawiki::store::Since\">Since</a>",synthetic:false,types:["tamawiki::store::Since"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"tamawiki/store/struct.Content.html\" title=\"struct tamawiki::store::Content\">Content</a>",synthetic:false,types:["tamawiki::store::Content"]},{text:"impl <a class=\"trait\" href=\"actix/handler/trait.Message.html\" title=\"trait actix::handler::Message\">Message</a> for <a class=\"struct\" href=\"tamawiki/store/struct.ContentAt.html\" title=\"struct tamawiki::store::ContentAt\">ContentAt</a>",synthetic:false,types:["tamawiki::store::ContentAt"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
